### ISSUE TITLE
How to use `vendor` as mount for PHP/composer apps?

### ISSUE THREAD

**Issue by matthewerskine** [hvalle/drone-gcs-cache#1]
Hi, thanks for making this plugin!

I'm trying to get this working in my pipeline for a PHP app, I'm using a pipeline like this (shortened for brevity):

```yaml
clone:
  git:
    image: plugins/git
    tags: true
pipeline:
  restore-cache:
    image: homerovalle/drone-gcs-cache
    pull: true
    bucket: ci-build-cache-erskine-io
    secrets: [ GCS_CACHE_JSON_KEY ]
    restore: true

  push-image:
    image: plugins/gcr
    repo: erskine-io/curries-legacy
    secrets: [ google_credentials ]

  rebuild-cache:
    image: homerovalle/drone-gcs-cache
    pull: true
    bucket: my-bucket
    secrets: [ GCS_CACHE_JSON_KEY ]
    rebuild: true
    mount:
      - vendor

  flush-cache:
    image: homerovalle/drone-gcs-cache
    pull: true
    bucket: my-bucket
    secrets: [ GCS_CACHE_JSON_KEY ]
    flush: true
    flush_age: 14
```

The `vendor` folder is created during the image push via the GCR plugin. I'm getting this error when running the pipeline:

`stat vendor: no such file or directory`

How can I persist the vendor folder through to the caching stage to avoid this?

Thanks for any help.
